name: ğŸš€  Deployment
on:
  push:
    branches:
      - main
      - develop
  pull_request: {}

jobs:
  lint:
    name: â¬£ ESLint
    # needs: [cache]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘  Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "50"
      - name: "âš¡ï¸  Install Deps"
        uses: ./.github/deps
      - name: Codegen
        run: pnpm run codegen --filter="web"

      - name: ğŸ”¬  Lint
        run: pnpm run lint

  jest:
    name: ğŸƒ  Jest
    # needs: [cache]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘  Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "50"
      - name: "âš¡ï¸  Install Deps"
        uses: ./.github/deps
      - name: Codegen
        run: pnpm run codegen --filter="web"

      - name: ğŸ‘·  Test
        run: pnpm run test:cov

  build:
    name: ğŸ‘·  Build
    # needs: [cache]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘  Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "50"
      - name: "âš¡ï¸  Install Deps"
        uses: ./.github/deps
      - name: ğŸ‘·  Build
        run: pnpm run schema && pnpm run build
